"""
Distribution Validation Metrics for Synthetic Samples
======================================================
Rigorous statistical validation of synthetic network traffic samples
generated by the diffusion model against real training data.

Metrics implemented:
  1. MMD (Maximum Mean Discrepancy) - with RBF kernel
  2. KL Divergence & JS Divergence - discretized feature-wise
  3. Wasserstein Distance (Earth Mover's Distance)
  4. Correlation Matrix Distance
  5. t-SNE / PCA visualization
  6. Feature-wise distribution plots (histogram/KDE)

Usage:
    python distribution_metrics.py --real_data ./data/real.npy --synth_data ./data/synthetic.npy

Author: [Your Name]
"""

import numpy as np
import torch
from typing import Dict, List, Optional, Tuple, Callable
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
from sklearn.neighbors import NearestNeighbors
from scipy.spatial.distance import cdist
from scipy.stats import entropy, ks_2samp, wasserstein_distance
import matplotlib
matplotlib.use('Agg')  # Non-interactive backend
import matplotlib.pyplot as plt
import seaborn as sns
import json
import os
import warnings
warnings.filterwarnings('ignore')


# ============================================================================
# 1. Maximum Mean Discrepancy (MMD)
# ============================================================================

def rbf_kernel(X: torch.Tensor, Y: torch.Tensor, sigma: Optional[float] = None) -> torch.Tensor:
    """Compute RBF kernel matrix between X and Y."""
    X_norm = (X ** 2).sum(dim=1, keepdim=True)
    Y_norm = (Y ** 2).sum(dim=1, keepdim=True)
    dist = X_norm + Y_norm.T - 2.0 * torch.mm(X, Y.T)
    dist = torch.clamp(dist, min=0.0)

    if sigma is None:
        # Median heuristic for bandwidth
        with torch.no_grad():
            all_dist = dist.flatten()
            sigma = torch.sqrt(0.5 * torch.median(all_dist[all_dist > 0]))
            sigma = torch.clamp(sigma, min=1e-3)

    return torch.exp(-dist / (2.0 * sigma ** 2))


def compute_mmd(X: torch.Tensor, Y: torch.Tensor, sigma: Optional[float] = None) -> Dict:
    """
    Compute MMD^2 (biased estimator) and return with p-value approximation.
    
    Lower MMD = more similar distributions.
    MMD = 0 means identical distributions (in RKHS).
    """
    n, m = X.size(0), Y.size(0)

    K_xx = rbf_kernel(X, X, sigma)
    K_yy = rbf_kernel(Y, Y, sigma)
    K_xy = rbf_kernel(X, Y, sigma)

    # Biased MMD^2 estimator: ||E[phi(x)] - E[phi(y)]||^2
    mmd2 = (K_xx.sum() - K_xx.trace()) / (n * (n - 1)) + \
           (K_yy.sum() - K_yy.trace()) / (m * (m - 1)) - \
           2.0 * K_xy.mean()

    mmd = torch.sqrt(torch.clamp(mmd2, min=0.0))

    return {
        'mmd': mmd.item(),
        'mmd2': mmd2.item(),
        'sigma': sigma.item() if isinstance(sigma, torch.Tensor) else sigma,
    }


def compute_mmd_with_permutation(X: torch.Tensor, Y: torch.Tensor,
                                  n_permutations: int = 1000,
                                  sigma: Optional[float] = None) -> Dict:
    """
    Compute MMD with permutation test for p-value.
    p < 0.05 → distributions are significantly different.
    """
    result = compute_mmd(X, Y, sigma)
    mmd_obs = result['mmd']

    # Permutation test
    combined = torch.cat([X, Y], dim=0)
    n = X.size(0)
    mmd_perms = []

    for _ in range(n_permutations):
        idx = torch.randperm(combined.size(0))
        X_perm = combined[idx[:n]]
        Y_perm = combined[idx[n:]]
        perm_result = compute_mmd(X_perm, Y_perm, sigma)
        mmd_perms.append(perm_result['mmd'])

    mmd_perms = np.array(mmd_perms)
    p_value = (np.sum(mmd_perms >= mmd_obs) + 1) / (n_permutations + 1)

    result['p_value'] = p_value
    result['significant'] = p_value < 0.05
    result['permutation_threshold_95'] = np.percentile(mmd_perms, 95)

    return result


# ============================================================================
# 2. KL Divergence & JS Divergence
# ============================================================================

def compute_kl_js_divergence(X_real: np.ndarray, X_synth: np.ndarray,
                              n_bins: int = 50, eps: float = 1e-10) -> Dict:
    """
    Compute per-feature KL and JS divergence.
    
    KL(P||Q): 0 = identical, higher = more different
    JS(P||Q): 0 to log(2) ≈ 0.693 (bounded, symmetric)
    """
    n_features = X_real.shape[1]
    kl_divs = []
    js_divs = []
    ks_stats = []
    ks_pvals = []

    for i in range(n_features):
        # Determine common bin range
        all_vals = np.concatenate([X_real[:, i], X_synth[:, i]])
        bins = np.linspace(np.min(all_vals), np.max(all_vals), n_bins)

        # Histograms
        p_real, _ = np.histogram(X_real[:, i], bins=bins, density=True)
        p_synth, _ = np.histogram(X_synth[:, i], bins=bins, density=True)

        # Add small epsilon to avoid log(0)
        p_real = p_real + eps
        p_synth = p_synth + eps
        p_real = p_real / p_real.sum()
        p_synth = p_synth / p_synth.sum()

        # KL divergence: KL(P_real || P_synth)
        kl = entropy(p_real, p_synth)

        # JS divergence: symmetric version
        m = 0.5 * (p_real + p_synth)
        js = 0.5 * entropy(p_real, m) + 0.5 * entropy(p_synth, m)

        kl_divs.append(kl)
        js_divs.append(js)

        # Kolmogorov-Smirnov test
        ks_stat, ks_p = ks_2samp(X_real[:, i], X_synth[:, i])
        ks_stats.append(ks_stat)
        ks_pvals.append(ks_p)

    # Summary statistics
    return {
        'kl_divergence': {
            'mean': float(np.mean(kl_divs)),
            'std': float(np.std(kl_divs)),
            'min': float(np.min(kl_divs)),
            'max': float(np.max(kl_divs)),
            'per_feature': [float(v) for v in kl_divs],
        },
        'js_divergence': {
            'mean': float(np.mean(js_divs)),
            'std': float(np.std(js_divs)),
            'min': float(np.min(js_divs)),
            'max': float(np.max(js_divs)),
            'per_feature': [float(v) for v in js_divs],
        },
        'ks_test': {
            'mean_stat': float(np.mean(ks_stats)),
            'mean_pvalue': float(np.mean(ks_pvals)),
            'features_reject_h0_5pct': int(np.sum(np.array(ks_pvals) < 0.05)),
            'n_features': n_features,
        }
    }


# ============================================================================
# 3. Wasserstein Distance (Earth Mover's Distance)
# ============================================================================

def compute_wasserstein_distance(X_real: np.ndarray, X_synth: np.ndarray) -> Dict:
    """Compute per-feature Wasserstein-1 distance."""
    n_features = X_real.shape[1]
    distances = []

    for i in range(n_features):
        wd = wasserstein_distance(X_real[:, i], X_synth[:, i])
        distances.append(wd)

    return {
        'wasserstein': {
            'mean': float(np.mean(distances)),
            'std': float(np.std(distances)),
            'min': float(np.min(distances)),
            'max': float(np.max(distances)),
            'per_feature': [float(v) for v in distances],
        }
    }


# ============================================================================
# 4. Correlation Matrix Distance
# ============================================================================

def compute_correlation_distance(X_real: np.ndarray, X_synth: np.ndarray) -> Dict:
    """
    Compare correlation structures between real and synthetic data.
    Measures how well pairwise feature correlations are preserved.
    """
    corr_real = np.corrcoef(X_real.T)
    corr_synth = np.corrcoef(X_synth.T)

    # Frobenius norm of difference
    corr_diff = corr_real - corr_synth
    frob_distance = np.linalg.norm(corr_diff, 'fro')

    # Mean absolute difference
    triu_idx = np.triu_indices_from(corr_real, k=1)
    mean_abs_diff = np.mean(np.abs(corr_diff[triu_idx]))
    max_abs_diff = np.max(np.abs(corr_diff[triu_idx]))

    return {
        'correlation_distance': {
            'frobenius_norm': float(frob_distance),
            'mean_abs_diff': float(mean_abs_diff),
            'max_abs_diff': float(max_abs_diff),
            'shape': corr_real.shape,
        }
    }


# ============================================================================
# 5. Coverage & Diversity Metrics
# ============================================================================

def compute_coverage_metrics(X_real: np.ndarray, X_synth: np.ndarray,
                              k: int = 5) -> Dict:
    """
    Coverage and diversity metrics for synthetic data quality.
    
    - recall@k: fraction of real samples that have a synthetic neighbor
    - precision@k: fraction of synthetic samples that have a real neighbor
    - coverage: fraction of real data manifold covered by synthetic samples
    """
    nn_real = NearestNeighbors(n_neighbors=k, metric='euclidean').fit(X_real)
    nn_synth = NearestNeighbors(n_neighbors=k, metric='euclidean').fit(X_synth)

    # Precision: for each synth sample, how many of its k nearest neighbors are real?
    dist_s2r, idx_s2r = nn_real.kneighbors(X_synth)
    precision = np.mean([len(np.unique(idx)) / k for idx in idx_s2r])

    # Recall: for each real sample, how many of its k nearest neighbors are synth?
    dist_r2s, idx_r2s = nn_synth.kneighbors(X_real)
    recall = np.mean([len(np.unique(idx)) / k for idx in idx_r2s])

    return {
        'coverage': {
            'precision_at_k': float(precision),
            'recall_at_k': float(recall),
            'density': float(precision * recall) / (precision + recall + 1e-10),
            'k': k,
        }
    }


# ============================================================================
# 6. Principal Component Analysis
# ============================================================================

def compute_pca_metrics(X_real: np.ndarray, X_synth: np.ndarray,
                         n_components: int = 10) -> Dict:
    """
    Compare explained variance ratios and PCA projections.
    """
    # Fit PCA on real data, transform both
    pca = PCA(n_components=min(n_components, min(X_real.shape)))
    pca.fit(X_real)

    # Project both
    proj_real = pca.transform(X_real)
    proj_synth = pca.transform(X_synth)

    # Compare explained variance captured by synthetic data
    var_real = np.var(proj_real, axis=0)
    var_synth = np.var(proj_synth, axis=0)
    var_ratio = var_synth / (var_real + 1e-10)

    return {
        'pca': {
            'explained_variance_ratio': [float(v) for v in pca.explained_variance_ratio_],
            'cumulative_variance': float(np.cumsum(pca.explained_variance_ratio_)[n_components - 1]),
            'variance_ratio_real_vs_synth': [float(v) for v in var_ratio],
            'n_components_used': n_components,
        }
    }


# ============================================================================
# 7. Full Validation Pipeline
# ============================================================================

def full_distribution_validation(
    X_real: np.ndarray,
    X_synth: np.ndarray,
    feature_names: Optional[List[str]] = None,
    output_dir: str = './validation_results',
    n_permutations: int = 200,
    n_bins: int = 50,
    use_tsne: bool = True,
) -> Dict:
    """
    Run all distribution validation metrics and generate plots.
    
    Args:
        X_real:   Real training samples (n_real, n_features)
        X_synth:  Synthetic samples (n_synth, n_features)
        feature_names: Optional feature names for plots
        output_dir: Output directory for results and plots
        n_permutations: Number of permutations for MMD test
        n_bins: Number of bins for KL/JS divergence
        use_tsne: Whether to generate t-SNE plot
    
    Returns:
        Dictionary with all metrics
    """
    os.makedirs(output_dir, exist_ok=True)
    
    if feature_names is None:
        feature_names = [f'F{i}' for i in range(X_real.shape[1])]

    print("=" * 60)
    print("Distribution Validation - Full Report")
    print(f"Real samples:    {X_real.shape}")
    print(f"Synth samples:   {X_synth.shape}")
    print(f"Features:        {X_real.shape[1]}")
    print("=" * 60)

    # Convert to torch for MMD
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    X_real_t = torch.FloatTensor(X_real).to(device)
    X_synth_t = torch.FloatTensor(X_synth).to(device)

    results = {}

    # 1. MMD
    print("\n[1/6] Computing MMD with permutation test...")
    mmd_result = compute_mmd_with_permutation(X_real_t, X_synth_t, n_permutations)
    results['mmd'] = mmd_result
    print(f"  MMD = {mmd_result['mmd']:.6f} "
          f"(p = {mmd_result['p_value']:.4f}, "
          f"{'SIGNIFICANT' if mmd_result['significant'] else 'NOT significant'})")

    # 2. KL & JS Divergence
    print("\n[2/6] Computing KL/JS divergence and KS tests...")
    div_result = compute_kl_js_divergence(X_real, X_synth, n_bins)
    results['divergence'] = div_result
    print(f"  KL mean: {div_result['kl_divergence']['mean']:.6f}")
    print(f"  JS mean: {div_result['js_divergence']['mean']:.6f}")
    print(f"  KS reject@5%: {div_result['ks_test']['features_reject_h0_5pct']}/"
          f"{div_result['ks_test']['n_features']} features")

    # 3. Wasserstein Distance
    print("\n[3/6] Computing Wasserstein distance...")
    wasser_result = compute_wasserstein_distance(X_real, X_synth)
    results['wasserstein'] = wasser_result
    print(f"  Wasserstein mean: {wasser_result['wasserstein']['mean']:.6f}")

    # 4. Correlation Distance
    print("\n[4/6] Computing correlation structure preservation...")
    corr_result = compute_correlation_distance(X_real, X_synth)
    results['correlation'] = corr_result
    print(f"  Frobenius norm: {corr_result['correlation_distance']['frobenius_norm']:.4f}")
    print(f"  Mean abs diff:  {corr_result['correlation_distance']['mean_abs_diff']:.4f}")

    # 5. Coverage
    print("\n[5/6] Computing coverage metrics (precision/recall@k)...")
    cov_result = compute_coverage_metrics(X_real, X_synth)
    results['coverage'] = cov_result
    print(f"  Precision@k: {cov_result['coverage']['precision_at_k']:.4f}")
    print(f"  Recall@k:    {cov_result['coverage']['recall_at_k']:.4f}")

    # 6. PCA
    print("\n[6/6] Computing PCA analysis...")
    pca_result = compute_pca_metrics(X_real, X_synth)
    results['pca'] = pca_result

    # --- Generate Plots ---
    print("\nGenerating plots...")

    # t-SNE visualization
    if use_tsne:
        _generate_tsne_plot(X_real, X_synth, output_dir)

    # PCA visualization
    _generate_pca_plot(X_real, X_synth, output_dir)

    # Feature-wise histogram comparison (sample up to 16 features)
    _generate_feature_histograms(X_real, X_synth, feature_names, output_dir)

    # Correlation matrix comparison
    _generate_correlation_plots(X_real, X_synth, feature_names, output_dir)

    # Summary radar chart
    _generate_summary_radar(results, output_dir)

    # Save all results as JSON
    # Convert numpy arrays and tensors
    serializable = json.loads(json.dumps(results, cls=_NumPyEncoder))
    result_path = os.path.join(output_dir, 'distribution_validation_results.json')
    with open(result_path, 'w') as f:
        json.dump(serializable, f, indent=2)
    print(f"\nResults saved to {result_path}")

    return results


# ============================================================================
# 8. Visualization Functions
# ============================================================================

def _generate_tsne_plot(X_real: np.ndarray, X_synth: np.ndarray,
                         output_dir: str, perplexity: int = 30):
    """Generate t-SNE comparison plot."""
    n_real = X_real.shape[0]
    combined = np.concatenate([X_real, X_synth], axis=0)

    # Subsample if too large
    max_samples = 5000
    if combined.shape[0] > max_samples:
        n_real_o = X_real.shape[0]
        n_synth = X_synth.shape[0]
        n_real_sub = min(n_real_o, max_samples // 2)
        n_synth_sub = min(n_synth, max_samples - n_real_sub)
        idx_real = np.random.choice(n_real_o, n_real_sub, replace=False)
        idx_synth = np.random.choice(n_synth, n_synth_sub, replace=False) + n_real_o
        idx = np.concatenate([idx_real, idx_synth])
        combined = combined[idx]
        labels = np.array(['Real'] * n_real_sub + ['Synth'] * n_synth_sub)
    else:
        labels = np.array(['Real'] * n_real + ['Synth'] * X_synth.shape[0])

    # PCA pre-reduction for t-SNE speed
    if combined.shape[1] > 50:
        pca = PCA(n_components=min(50, combined.shape[1]))
        combined = pca.fit_transform(combined)

    tsne = TSNE(n_components=2, perplexity=min(perplexity, combined.shape[0] - 1),
                random_state=42, n_iter=1000)
    emb = tsne.fit_transform(combined)

    fig, ax = plt.subplots(1, 1, figsize=(10, 8))
    colors = {'Real': '#2196F3', 'Synth': '#FF5722'}
    for label in ['Real', 'Synth']:
        mask = labels == label
        ax.scatter(emb[mask, 0], emb[mask, 1], c=colors[label], label=label,
                   alpha=0.6, s=10)
    ax.set_title('t-SNE: Real vs Synthetic Samples', fontsize=14)
    ax.legend()
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'tsne_comparison.png'), dpi=150)
    plt.close()
    print(f"  [Plot] t-SNE saved to {output_dir}/tsne_comparison.png")


def _generate_pca_plot(X_real: np.ndarray, X_synth: np.ndarray,
                        output_dir: str):
    """Generate PCA comparison plot (2D projection)."""
    pca = PCA(n_components=2)
    combined = np.concatenate([X_real, X_synth], axis=0)
    proj = pca.fit_transform(combined)

    n_real = X_real.shape[0]
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    # PCA projection
    axes[0].scatter(proj[:n_real, 0], proj[:n_real, 1], c='#2196F3',
                    label='Real', alpha=0.5, s=8)
    axes[0].scatter(proj[n_real:, 0], proj[n_real:, 1], c='#FF5722',
                    label='Synthetic', alpha=0.5, s=8)
    axes[0].set_xlabel(f'PC1 ({pca.explained_variance_ratio_[0]:.1%})')
    axes[0].set_ylabel(f'PC2 ({pca.explained_variance_ratio_[1]:.1%})')
    axes[0].set_title('PCA Projection')
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)

    # Explained variance
    n_plot = min(20, len(pca.explained_variance_ratio_))
    axes[1].bar(range(n_plot), pca.explained_variance_ratio_[:n_plot],
                color='#4CAF50', alpha=0.7)
    axes[1].plot(range(n_plot), np.cumsum(pca.explained_variance_ratio_)[:n_plot],
                 'r-o', markersize=4)
    axes[1].axhline(0.95, color='gray', linestyle='--', alpha=0.5)
    axes[1].set_xlabel('Principal Component')
    axes[1].set_ylabel('Explained Variance Ratio')
    axes[1].set_title('PCA Explained Variance')
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'pca_comparison.png'), dpi=150)
    plt.close()
    print(f"  [Plot] PCA saved to {output_dir}/pca_comparison.png")


def _generate_feature_histograms(X_real: np.ndarray, X_synth: np.ndarray,
                                  feature_names: List[str], output_dir: str,
                                  max_features: int = 16):
    """Generate per-feature histogram comparison."""
    n_features = X_real.shape[1]
    n_plot = min(max_features, n_features)
    n_cols = 4
    n_rows = (n_plot + n_cols - 1) // n_cols

    fig, axes = plt.subplots(n_rows, n_cols, figsize=(n_cols * 4, n_rows * 3))
    axes = axes.flatten()

    for i in range(n_plot):
        ax = axes[i]
        ax.hist(X_real[:, i], bins=50, alpha=0.6, color='#2196F3',
                label='Real', density=True)
        ax.hist(X_synth[:, i], bins=50, alpha=0.6, color='#FF5722',
                label='Synthetic', density=True)
        ax.set_title(feature_names[i] if i < len(feature_names) else f'F{i}')
        ax.legend(fontsize=6)
        ax.grid(True, alpha=0.2)

    # Hide empty subplots
    for i in range(n_plot, len(axes)):
        axes[i].set_visible(False)

    plt.suptitle('Feature-wise Distribution Comparison', fontsize=14)
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'feature_histograms.png'), dpi=150)
    plt.close()
    print(f"  [Plot] Feature histograms saved to {output_dir}/feature_histograms.png")


def _generate_correlation_plots(X_real: np.ndarray, X_synth: np.ndarray,
                                 feature_names: List[str], output_dir: str):
    """Generate correlation matrix comparison."""
    corr_real = np.corrcoef(X_real.T)
    corr_synth = np.corrcoef(X_synth.T)
    corr_diff = np.abs(corr_real - corr_synth)

    fig, axes = plt.subplots(1, 3, figsize=(18, 6))

    vmin, vmax = -1, 1
    sns.heatmap(corr_real, ax=axes[0], cmap='RdBu_r', vmin=vmin, vmax=vmax,
                xticklabels=False, yticklabels=False, cbar_kws={'label': 'Correlation'})
    axes[0].set_title('Real Data Correlation')

    sns.heatmap(corr_synth, ax=axes[1], cmap='RdBu_r', vmin=vmin, vmax=vmax,
                xticklabels=False, yticklabels=False, cbar_kws={'label': 'Correlation'})
    axes[1].set_title('Synthetic Data Correlation')

    sns.heatmap(corr_diff, ax=axes[2], cmap='YlOrRd',
                xticklabels=False, yticklabels=False, cbar_kws={'label': '|Diff|'})
    axes[2].set_title('Absolute Difference')

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'correlation_comparison.png'), dpi=150)
    plt.close()
    print(f"  [Plot] Correlation matrices saved to {output_dir}/correlation_comparison.png")


def _generate_summary_radar(results: Dict, output_dir: str):
    """Generate radar chart summarizing all metrics."""
    metrics = {
        'MMD\n(lower=better)': 1.0 - min(results.get('mmd', {}).get('mmd', 0) * 10, 1.0),
        'JS Div.\n(lower=better)': 1.0 - min(results.get('divergence', {}).get('js_divergence', {}).get('mean', 0) * 5, 1.0),
        'KL Div.\n(lower=better)': 1.0 - min(results.get('divergence', {}).get('kl_divergence', {}).get('mean', 0) * 2, 1.0),
        'Correlation\n(higher=better)': 1.0 - min(results.get('correlation', {}).get('correlation_distance', {}).get('mean_abs_diff', 0) * 5, 1.0),
        'Coverage\n(higher=better)': results.get('coverage', {}).get('coverage', {}).get('density', 0),
    }

    labels = list(metrics.keys())
    values = list(metrics.values())
    N = len(labels)
    angles = [n / float(N) * 2 * np.pi for n in range(N)]
    values += values[:1]
    angles += angles[:1]

    fig, ax = plt.subplots(figsize=(8, 8), subplot_kw=dict(polar=True))
    ax.plot(angles, values, 'o-', linewidth=2, color='#2196F3')
    ax.fill(angles, values, alpha=0.25, color='#2196F3')
    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(labels, fontsize=10)
    ax.set_ylim(0, 1)
    ax.set_title('Synthetic Sample Quality Summary', fontsize=14, pad=20)
    ax.grid(True)

    # Add score
    overall = np.mean(list(metrics.values()))
    ax.text(0, 0, f'Overall: {overall:.3f}', fontsize=12, ha='center',
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'quality_radar.png'), dpi=150)
    plt.close()
    print(f"  [Plot] Quality radar saved to {output_dir}/quality_radar.png")


# ============================================================================
# 9. JSON Serialization Helper
# ============================================================================

class _NumPyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, (np.integer,)):
            return int(obj)
        elif isinstance(obj, (np.floating,)):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        elif isinstance(obj, (np.bool_,)):
            return bool(obj)
        elif isinstance(obj, (torch.Tensor,)):
            return obj.cpu().numpy().tolist()
        return super().default(obj)


# ============================================================================
# 10. Command Line Interface
# ============================================================================

if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description='Distribution Validation for Synthetic Samples')
    parser.add_argument('--real', type=str, required=True,
                        help='Path to real data (numpy .npy file)')
    parser.add_argument('--synth', type=str, required=True,
                        help='Path to synthetic data (numpy .npy file)')
    parser.add_argument('--output', type=str, default='./validation_results',
                        help='Output directory')
    parser.add_argument('--n_perms', type=int, default=200,
                        help='Number of MMD permutations')
    parser.add_argument('--n_bins', type=int, default=50,
                        help='Number of bins for KL/JS')
    parser.add_argument('--no_tsne', action='store_true',
                        help='Skip t-SNE plot')
    args = parser.parse_args()

    X_real = np.load(args.real)
    X_synth = np.load(args.synth)

    results = full_distribution_validation(
        X_real, X_synth,
        output_dir=args.output,
        n_permutations=args.n_perms,
        n_bins=args.n_bins,
        use_tsne=not args.no_tsne,
    )
